import type { HelpCategory } from "./types";

export const HELP_CATEGORIES: HelpCategory[] = [
  {
    id: "getting-started",
    slug: "getting-started",
    title: "Getting Started",
    description: "Create your account, set up your profile, and learn the basics.",
    icon: "Rocket",
    order: 1,
    roles: ["all"],
  },
  {
    id: "venues",
    slug: "venues",
    title: "Venues & Bookings",
    description: "Find courts and grounds, check availability, and book slots.",
    icon: "MapPin",
    order: 2,
    roles: ["all"],
  },
  {
    id: "bookings",
    slug: "bookings",
    title: "Bookings",
    description: "Manage bookings, cancellations, and booking history.",
    icon: "Calendar",
    order: 3,
    roles: ["all"],
  },
  {
    id: "open-play",
    slug: "open-play",
    title: "Open Play",
    description: "Discover and join open sessions with other players.",
    icon: "Zap",
    order: 4,
    roles: ["player", "all"],
  },
  {
    id: "training",
    slug: "training",
    title: "Training",
    description: "Find trainers, join batches, and track training progress.",
    icon: "Dumbbell",
    order: 5,
    roles: ["player", "coach", "trainer", "all"],
  },
  {
    id: "matches",
    slug: "matches",
    title: "Matches & Scoring",
    description: "Create matches, score games, and review match history.",
    icon: "Target",
    order: 6,
    roles: ["player", "all"],
  },
  {
    id: "stats",
    slug: "stats",
    title: "Stats & Leaderboards",
    description: "Track performance, ratings, and climb the leaderboard.",
    icon: "BarChart3",
    order: 7,
    roles: ["player", "all"],
  },
  {
    id: "tournaments",
    slug: "tournaments",
    title: "Tournaments",
    description: "Discover events, register teams, and follow fixtures.",
    icon: "Trophy",
    order: 8,
    roles: ["all"],
  },
  {
    id: "payments",
    slug: "payments",
    title: "Payments & Refunds",
    description: "Understand payments, receipts, wallet, and refunds.",
    icon: "CreditCard",
    order: 9,
    roles: ["all"],
  },
  {
    id: "reviews",
    slug: "reviews",
    title: "Reviews",
    description: "Rate venues and trainers after your sessions.",
    icon: "Star",
    order: 10,
    roles: ["player", "all"],
  },
  {
    id: "notifications",
    slug: "notifications",
    title: "Notifications",
    description: "Stay updated on bookings, matches, and invitations.",
    icon: "Bell",
    order: 11,
    roles: ["all"],
  },
  {
    id: "account",
    slug: "account",
    title: "Account & Security",
    description: "Manage profile, sports preferences, and security settings.",
    icon: "User",
    order: 12,
    roles: ["all"],
  },
  {
    id: "troubleshooting",
    slug: "troubleshooting",
    title: "Troubleshooting",
    description: "Fix common issues with login, payments, and bookings.",
    icon: "Wrench",
    order: 13,
    roles: ["all"],
  },
  {
    id: "faq",
    slug: "faq",
    title: "FAQ",
    description: "Quick answers to the most common questions.",
    icon: "HelpCircle",
    order: 14,
    roles: ["all"],
  },
];

export function getCategoryBySlug(slug: string): HelpCategory | undefined {
  return HELP_CATEGORIES.find((c) => c.slug === slug || c.id === slug);
}
